App\Entity\Book:
    properties:
        title:
            - NotBlank: ~
              Length:
                  min: 2
                  max: 10
                  minMessage: 'Your first name must be at least {{ limit }} characters long'
                  maxMessage: 'Your first name cannot be longer than {{ limit }} characters'